name: simon

on:
  push: 
    branch: [master]
#dfgdf
jobs: 
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}/simon:latest
    
    steps:
      - name: Login to docker.io
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PWD }}
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_NAME }}/simon:latest -f Dockerfile .
      - name: Push image to docker.io
        run: docker push ${{ secrets.DOCKER_NAME }}/simon:latest

  deploy_on_server:
    needs: [build_and_pub]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.PRIVATE_SSH }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no amori@195.49.215.85 'cd ~/family && docker pull ${{ secrets.DOCKER_NAME }}/simon:latest && docker-compose up -d && docker system prune -f'
